# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# !!! MAKE IT MULTILINGUAL
# https://www.sylvaindurand.org/making-jekyll-multilingual/

# !!! CHEAT SHEET
# http://jekyll.tips/jekyll-cheat-sheet/

# Site settings
title: 
  nl: Luc Hamblok
  #fr: Luc Hamblok
  en: Luc Hamblok
email: luc.hamblok@telenet.be
#description: > # this means to ignore newlines until "baseurl:"
#  Evelyne Hamblok Architectuurproject
description:
  nl: Luc Hamblok
  #fr: Luc Hamblok
  en: Luc Hamblok
#feed:
#  nl: /rss.xml
#  fr: /flux.xml
#  en: /feed.xml

collections:
  articles:
    output: true
    permalink: /:path/

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.luchamblok.be" # the base hostname & protocol for your site
permalink: none
#twitter_username: evelynehamblok
#github_username:  evelynehamblok

# Build settings
markdown: kramdown

# Port
port: 8080
